"""Region Model

Revision ID: 5d2d4f8f5315
Revises: 
Create Date: 2026-01-18 13:24:26.768293

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d4f8f5315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region_code', sa.String(length=40), nullable=False),
    sa.Column('general_location_description', sa.String(length=400), nullable=True),
    sa.Column('primary_city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='regionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('regional_manager_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_country'), 'regions', ['country'], unique=False)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.create_index(op.f('ix_regions_primary_city'), 'regions', ['primary_city'], unique=False)
    op.create_index(op.f('ix_regions_region_code'), 'regions', ['region_code'], unique=True)
    op.create_index(op.f('ix_regions_regional_manager_id'), 'regions', ['regional_manager_id'], unique=False)
    op.create_index(op.f('ix_regions_state'), 'regions', ['state'], unique=False)
    op.create_index(op.f('ix_regions_status'), 'regions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_status'), table_name='regions')
    op.drop_index(op.f('ix_regions_state'), table_name='regions')
    op.drop_index(op.f('ix_regions_regional_manager_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_region_code'), table_name='regions')
    op.drop_index(op.f('ix_regions_primary_city'), table_name='regions')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_country'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
