"""Centers Model

Revision ID: a83f9ce00ea6
Revises: 3fdffede0c84
Create Date: 2026-01-18 13:53:22.313098

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83f9ce00ea6'
down_revision: Union[str, Sequence[str], None] = '3fdffede0c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('center_code', sa.String(length=40), nullable=False),
    sa.Column('street_address', sa.String(length=400), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gst_number', sa.String(length=40), nullable=True),
    sa.Column('place_of_supply', sa.String(length=60), nullable=True),
    sa.Column('gst_status', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='centerstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('cdc_manager_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centers_cdc_manager_id'), 'centers', ['cdc_manager_id'], unique=False)
    op.create_index(op.f('ix_centers_center_code'), 'centers', ['center_code'], unique=True)
    op.create_index(op.f('ix_centers_city'), 'centers', ['city'], unique=False)
    op.create_index(op.f('ix_centers_id'), 'centers', ['id'], unique=False)
    op.create_index(op.f('ix_centers_name'), 'centers', ['name'], unique=False)
    op.create_index(op.f('ix_centers_region_id'), 'centers', ['region_id'], unique=False)
    op.create_index(op.f('ix_centers_status'), 'centers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centers_status'), table_name='centers')
    op.drop_index(op.f('ix_centers_region_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_name'), table_name='centers')
    op.drop_index(op.f('ix_centers_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_city'), table_name='centers')
    op.drop_index(op.f('ix_centers_center_code'), table_name='centers')
    op.drop_index(op.f('ix_centers_cdc_manager_id'), table_name='centers')
    op.drop_table('centers')
    # ### end Alembic commands ###
