"""Center Fix

Revision ID: a9095d93eec7
Revises: a83f9ce00ea6
Create Date: 2026-01-18 14:06:50.113478

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9095d93eec7'
down_revision: Union[str, Sequence[str], None] = 'a83f9ce00ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centers_cdc_manager_id'), table_name='centers')
    op.drop_column('centers', 'cdc_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('cdc_manager_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_centers_cdc_manager_id'), 'centers', ['cdc_manager_id'], unique=False)
    # ### end Alembic commands ###
